#!/bin/bash

echo "=== Real-Time Parameter Sync Test Script ==="
echo "This script provides manual testing steps for validating real-time parameter synchronization"
echo ""

echo "SETUP INSTRUCTIONS:"
echo "1. Load VCV Rack with the nt_emu module"
echo "2. Load a test plugin (e.g., gain.dylib) in the DistingNT module"
echo "3. Connect an oscillator or audio source to Input 1"
echo "4. Connect oscilloscopes/analyzers to Output 1, Output 2, and Output 3"
echo "5. Set the input routing parameter to route the audio to Input 1"
echo ""

echo "TEST PROCEDURES:"
echo ""
echo "=== Test 1: Basic Output Routing Sync ==="
echo "1. Enter menu (Left encoder press)"
echo "2. Navigate to an output routing parameter (e.g., 'Output')"
echo "3. Verify the parameter is currently set to 'Output 1'"
echo "4. Change from 'Output 1' to 'Output 2' using encoder"
echo "5. ✓ VERIFY: Audio immediately appears at Output 2 WITHOUT exiting menu"
echo "6. Change to 'Output 3'"
echo "7. ✓ VERIFY: Audio immediately moves to Output 3 WITHOUT exiting menu"
echo "8. Exit menu (Left encoder press)"
echo "9. ✓ VERIFY: Audio remains at Output 3 after menu exit"
echo ""

echo "=== Test 2: Input Routing Sync ==="
echo "1. Connect additional audio source to Input 2"
echo "2. Enter menu (Left encoder press)"
echo "3. Navigate to an input routing parameter"
echo "4. Change from 'Input 1' to 'Input 2'"
echo "5. ✓ VERIFY: Audio from Input 2 immediately becomes active WITHOUT exiting menu"
echo "6. Change back to 'Input 1'"
echo "7. ✓ VERIFY: Audio from Input 1 immediately becomes active WITHOUT exiting menu"
echo "8. Exit menu"
echo ""

echo "=== Test 3: Output Mode Sync ==="
echo "1. Enter menu"
echo "2. Navigate to an output mode parameter (if available)"
echo "3. Change from 'Direct' to 'Add' (or equivalent)"
echo "4. ✓ VERIFY: Output behavior changes immediately WITHOUT exiting menu"
echo "5. Exit menu"
echo ""

echo "=== Test 4: Multiple Parameter Changes ==="
echo "1. Enter menu"
echo "2. Change output routing from Output 1 to Output 2"
echo "3. Navigate to another routing parameter"
echo "4. Change input routing"
echo "5. Navigate back to output parameter"
echo "6. Change to Output 3"
echo "7. ✓ VERIFY: All changes applied immediately during menu interaction"
echo "8. Exit menu"
echo "9. ✓ VERIFY: All settings persist after menu exit"
echo ""

echo "=== Test 5: Performance Validation ==="
echo "1. Load a complex plugin with many routing parameters"
echo "2. Enter menu and rapidly change routing parameters"
echo "3. ✓ VERIFY: No audio glitches or dropouts during parameter changes"
echo "4. ✓ VERIFY: Smooth parameter transitions without crackling"
echo "5. Monitor CPU usage during rapid parameter changes"
echo "6. ✓ VERIFY: No significant performance degradation"
echo ""

echo "EXPECTED RESULTS:"
echo "✓ Routing changes apply immediately during menu editing"
echo "✓ No menu exit required for parameter changes to take effect"
echo "✓ Parameter display matches active routing at all times"
echo "✓ No audio glitches during parameter changes"
echo "✓ Settings persist correctly after menu exit"
echo "✓ No performance degradation"
echo ""

echo "If any test fails, the real-time parameter sync implementation needs adjustment."
echo "All tests should pass for successful implementation."